//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingListItem
    {
        public int SLIID { get; set; }
        public Nullable<int> SLID { get; set; }
        public int IID { get; set; }
        public Nullable<int> ITID { get; set; }
        public int QTY { get; set; }
    }
}
