//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEndMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        public int ITID { get; set; }
        public string ITName { get; set; }
    }
}
