//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace picture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseHoldItem
    {
        public int HHIID { get; set; }
        public int QTY { get; set; }
        public Nullable<int> SSID { get; set; }
        public Nullable<int> IID { get; set; }
        public Nullable<int> HHID { get; set; }
    
        public virtual HouseHold HouseHold { get; set; }
        public virtual Item Item { get; set; }
        public virtual StorageSpace StorageSpace { get; set; }
    }
}
