//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpToDateApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseHoldItem
    {
        public int HHIID { get; set; }
        public int QTY { get; set; }
        public Nullable<int> SSID { get; set; }
        public Nullable<int> IID { get; set; }
        public Nullable<int> HHID { get; set; }

        public HouseHoldItem() { }

        public HouseHoldItem(int ID, int qty)
        {
            HHIID = 1;
            IID = ID;
            QTY = qty;
            HHID = null ;
            SSID = null;

        }
    }
}
