//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace playingwithtables.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseHold
    {
        public int HHID { get; set; }
        public string HHName { get; set; }
        public int AdminUser { get; set; }
        public Nullable<int> RestrictedUsers { get; set; }
    }
}
