//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Weight { get; set; }
        public int QTY { get; set; }
        public string Cupboard { get; set; }
        public string Room { get; set; }
    }
}
