//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpToDateApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeItem
    {
        public int RecipeIID { get; set; }
        public Nullable<int> Item { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public int QTY { get; set; }
        public Nullable<int> Weight { get; set; }
    }
}
